import React, { useState } from 'react';
import { Card } from './Layout';
import { generateContent } from '../services/geminiService';
import { Brain, Sparkles, Loader2, Check, X, RotateCcw, MessageSquare } from 'lucide-react';
import { QuizQuestion } from '../types';

export const AIQuizSection = () => {
  const [questions, setQuestions] = useState<QuizQuestion[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [userAnswers, setUserAnswers] = useState<Record<number, number>>({});
  const [showResults, setShowResults] = useState(false);

  const startQuiz = async () => {
    setLoading(true);
    const prompt = `Generate 3 advanced multiple-choice questions about Binary Trees, Traversals, and AVL balancing. 
    Return strictly as a JSON array of objects with the following keys: "q" (string), "options" (string array of 4 items), "correct" (integer index), and "explanation" (string explaining why).`;
    
    try {
      const text = await generateContent(prompt, true);
      const data = JSON.parse(text);
      setQuestions(data);
      setUserAnswers({});
      setShowResults(false);
    } catch (e) {
      console.error("Quiz generation failed", e);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <Card className="border-t-4 border-t-purple-500">
        <div className="flex flex-col items-center justify-center py-12 sm:py-16 text-center">
          <Loader2 className="animate-spin text-purple-600 mb-4" size={40} />
          <h3 className="text-xl sm:text-2xl font-black text-gray-900 uppercase tracking-tight">Generating Challenge...</h3>
          <p className="text-gray-500 font-medium px-4">Gemini is tailoring questions to your skill level.</p>
        </div>
      </Card>
    );
  }

  if (!questions) {
    return (
      <div className="bg-gradient-to-br from-indigo-600 to-purple-700 rounded-3xl sm:rounded-[3rem] p-8 sm:p-12 text-white text-center shadow-2xl shadow-indigo-200">
        <div className="w-16 h-16 sm:w-20 sm:h-20 bg-white/10 rounded-2xl sm:rounded-3xl flex items-center justify-center mx-auto mb-6 sm:mb-8 backdrop-blur-md">
           <Brain size={32} className="text-white sm:hidden" />
           <Brain size={48} className="text-white hidden sm:block" />
        </div>
        <h3 className="text-2xl sm:text-4xl font-black mb-4 tracking-tight">Ready for a Brain Teaser?</h3>
        <p className="mb-8 sm:mb-10 text-indigo-100 text-base sm:text-lg font-medium opacity-90 max-w-md mx-auto leading-relaxed">
          Test your knowledge with dynamic questions generated by Gemini AI.
        </p>
        <button 
          onClick={startQuiz}
          className="bg-white text-indigo-700 w-full sm:w-auto px-10 py-4 sm:py-5 rounded-xl sm:rounded-2xl font-black shadow-xl hover:scale-105 active:scale-95 transition-all flex items-center justify-center gap-3 mx-auto text-lg"
        >
          <Sparkles size={24} />
          Start Smart Quiz
        </button>
      </div>
    );
  }

  return (
    <Card title="✨ Gemini Intelligence Check" className="border-t-4 border-t-purple-500">
      <div className="space-y-8 sm:space-y-12">
        {questions.map((q, qIdx) => (
          <div key={qIdx} className="border-b border-gray-100 last:border-0 pb-8 sm:pb-10 last:pb-0">
            <h4 className="font-black text-lg sm:text-xl text-gray-900 mb-4 sm:mb-6 leading-tight">{qIdx + 1}. {q.q}</h4>
            <div className="grid gap-2 sm:gap-3">
              {q.options.map((opt, optIdx) => {
                const isSelected = userAnswers[qIdx] === optIdx;
                const isCorrect = q.correct === optIdx;
                let btnClass = "w-full text-left p-4 sm:p-5 rounded-xl sm:rounded-2xl border-2 transition-all font-bold text-sm sm:text-base ";
                
                if (showResults) {
                  if (isCorrect) btnClass += "bg-emerald-50 border-emerald-500 text-emerald-800 shadow-sm";
                  else if (isSelected) btnClass += "bg-rose-50 border-rose-300 text-rose-700";
                  else btnClass += "bg-gray-50 border-gray-100 text-gray-400 opacity-50";
                } else {
                  btnClass += isSelected 
                    ? "bg-indigo-50 border-indigo-500 text-indigo-800 shadow-md ring-4 ring-indigo-50" 
                    : "bg-white border-gray-100 hover:border-indigo-200 hover:bg-gray-50 text-gray-700";
                }

                return (
                  <button 
                    key={optIdx} 
                    onClick={() => !showResults && setUserAnswers(prev => ({ ...prev, [qIdx]: optIdx }))}
                    disabled={showResults}
                    className={btnClass}
                  >
                    <div className="flex items-center justify-between">
                      <span className="flex-1">{opt}</span>
                      {showResults && isCorrect && <Check size={20} className="text-emerald-600 shrink-0 ml-2" />}
                      {showResults && isSelected && !isCorrect && <X size={20} className="text-rose-600 shrink-0 ml-2" />}
                    </div>
                  </button>
                );
              })}
            </div>
            {showResults && (
              <div className="mt-4 sm:mt-6 p-4 sm:p-6 bg-blue-50/50 text-blue-800 rounded-xl sm:rounded-2xl flex gap-3 sm:gap-4 border border-blue-100">
                <MessageSquare size={20} className="shrink-0 mt-1 text-blue-500" />
                <p className="text-xs sm:text-sm font-medium leading-relaxed"><strong>Insight:</strong> {q.explanation}</p>
              </div>
            )}
          </div>
        ))}
        
        {!showResults ? (
          <button 
            onClick={() => setShowResults(true)}
            className="w-full py-4 sm:py-5 bg-gray-900 text-white rounded-xl sm:rounded-2xl font-black text-lg hover:bg-gray-800 transition-all shadow-xl shadow-gray-200"
          >
            Submit Quiz
          </button>
        ) : (
          <button 
            onClick={startQuiz}
            className="w-full py-4 sm:py-5 bg-purple-600 text-white rounded-xl sm:rounded-2xl font-black text-lg hover:bg-purple-700 transition-all flex items-center justify-center gap-3 shadow-xl shadow-purple-100"
          >
            <RotateCcw size={24} /> Try Another Set
          </button>
        )}
      </div>
    </Card>
  );
};